/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <system_stm32f4xx.h>
#include <stdint.h>
#include <timer.h>
#include <Ucglib.h>

static ucg_t ucg;

int main(void)
{
    SystemCoreClockUpdate();                   // cấp clock
    TimerInit();                               // để khởi tạo chức năng timer.

    // Khởi tạo LCD
    Ucglib4WireSWSPI_begin(&ucg, UCG_FONT_MODE_SOLID);
    ucg_ClearScreen(&ucg);
    ucg_SetRotate180(&ucg);   // Xoay màn hình 180 độ


    ucg_SetFont(&ucg, ucg_font_6x10_tr); // chọn font nhỏ

        ucg_SetFontPosBaseline(&ucg);

        ucg_SetColor(&ucg, 0, 255, 255, 0);  // màu vàng

        ucg_SetRotate180(&ucg);

        ucg_DrawString(&ucg, 65, 128, 0, "Nhom6-TTCS");


    /* Loop forever */
    while (1)
    {
        processTimerScheduler();
    }
}
